name: New release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    # outputs:
    #   upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Get changelog
        id: get_changelog
        run: |
          previous_tag="$(git describe --tags --abbrev=0)"
          changelog="$(git log --pretty=format:"%h %s" "${previous_tag}"..HEAD)"
          echo -e "Changelog:\n${changelog}"
          echo "::set-output name=changelog::${changelog}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{ steps.get_changelog.outputs.changelog }}

      # - name: Delete release if anything goes wrong.
      #   if: ${{ failure() }}
      #   uses: author/action-rollback@master
      #   with:
      #     release_id: ${{ steps.create_release.id }}
      #     tag: ${{ github.ref }}
      #     always_delete_tag: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
